services:
  mariadb:
    image: mariadb:lts
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MARIADB_DATABASE=mailstic
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_RANDOM_ROOT_PASSWORD=1
    volumes:
      - mariadb_data:/data/db

volumes:
  