FROM ubuntu:22.04
WORKDIR /app

ENV PYTHONUNBUFFERED=1
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get upgrade -y && apt-get install -y wget software-properties-common && add-apt-repository ppa:deadsnakes/ppa && apt-get update && apt-get install -y python3.12 python3.12-distutils
RUN wget https://bootstrap.pypa.io/get-pip.py && python3.12 get-pip.py

COPY ./requirements.txt .
RUN python3 -m pip install --no-cache -r requirements.txt

COPY . .