FROM ubuntu:22.04
WORKDIR /app

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get upgrade -y && apt-get install -y wget python3 python3-pip

COPY ./requirements.txt .
RUN python3 -m pip install --no-cache -r requirements.txt

COPY . .