"""improves

Revision ID: 292977ee94af
Revises: 33601f627e2b
Create Date: 2024-11-10 09:37:05.763103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '292977ee94af'
down_revision: Union[str, None] = '33601f627e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('serial', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('problem', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_column('problem')
        batch_op.drop_column('serial')
        batch_op.drop_column('device')

    # ### end Alembic commands ###
