"""initial

Revision ID: d513b8aaad43
Revises: 
Create Date: 2024-11-10 00:37:43.131829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd513b8aaad43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pof',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('slug', name=op.f('pk_pof'))
    )
    op.create_table('thread',
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUCCESSFUL', name='threadstatus'), nullable=False),
    sa.Column('recogize_progress', sa.Enum('UNABLE_TO_RECOGNIZE_SN', 'UNABLE_TO_RECOGNIZE_PROBLEM', 'RECOGNIZE_SN_IN_PROGRESS', 'RECOGNIZE_PROBLEM_IN_PROGRESS', 'RECOGNIZE_SUCCESSFUL', name='recognizeprogress'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_thread'))
    )
    op.create_table('user',
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('login', name=op.f('pk_user'))
    )
    op.create_table('message',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], name=op.f('fk_message_thread_id_thread')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_table('qa',
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('pof_slug', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pof_slug'], ['pof.slug'], name=op.f('fk_qa_pof_slug_pof')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qa')
    op.drop_table('message')
    op.drop_table('user')
    op.drop_table('thread')
    op.drop_table('pof')
    # ### end Alembic commands ###
